"""
Synthetic AI-solution generator — no API key required.

Reads each human solution from data/raw/{problem_id}/ and produces a
stylistically distinct "AI-style" variant that is saved to
data/generated/{problem_id}/ in the same format that build_dataset.py expects.

The transformations deliberately mimic patterns that LLM-generated code
tends to show (verbose naming, docstrings, type hints, helper comments),
making them useful as *smoke-test* labels while real API-generated solutions
are collected separately.

Run instead of (or before) generate_ai_solutions.py:
    python scripts/generate_synthetic_solutions.py
"""

import ast
import re
import sys
from pathlib import Path

from loguru import logger
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config.settings import AI_SOLUTIONS_PER_PROBLEM, DATA_DIR, GENERATED_DIR, RAW_DIR

SELECTED_PATH = DATA_DIR / "selected_problems.txt"
MODEL_TAG = "synthetic_ai"


# ── Python transformer ─────────────────────────────────────────────────────

_PY_HEADER = '''\
"""Solution generated by AI assistant."""
from typing import List, Tuple, Optional

'''

_PY_ABBREVS = {
    r"\bn\b": "n_count",
    r"\bm\b": "m_count",
    r"\bi\b": "index",
    r"\bj\b": "inner_index",
    r"\bk\b": "k_val",
    r"\bans\b": "answer",
    r"\bres\b": "result",
    r"\bx\b": "x_val",
    r"\by\b": "y_val",
    r"\bv\b": "value",
    r"\ba\b": "arr",
    r"\bb\b": "b_val",
    r"\bcnt\b": "count",
    r"\bnum\b": "number",
}


def _transform_python(code: str) -> str:
    lines = code.splitlines()
    out = [_PY_HEADER.rstrip()]

    # Wrap the whole solution in a main() function with a docstring
    out.append("def solve_problem() -> None:")
    out.append('    """Read input, compute result, and print the answer."""')
    for line in lines:
        stripped = line.rstrip()
        if stripped.startswith("import ") or stripped.startswith("from "):
            continue  # already in header
        out.append("    " + stripped if stripped else "")
    out.append("")
    out.append("")
    out.append('if __name__ == "__main__":')
    out.append("    solve_problem()")

    result = "\n".join(out)

    # Rename single-letter variables (only in names, not strings)
    for pattern, replacement in _PY_ABBREVS.items():
        result = re.sub(pattern, replacement, result)

    return result


# ── C++ transformer ────────────────────────────────────────────────────────

_CPP_HEADER = """\
/**
 * @brief Competitive programming solution.
 * @details AI-generated solution using standard algorithms and data structures.
 */
#include <bits/stdc++.h>
using namespace std;

"""


def _transform_cpp(code: str) -> str:
    lines = code.splitlines()
    body_lines = []
    for line in lines:
        s = line.strip()
        if s.startswith("#include") or s.startswith("using namespace"):
            continue
        body_lines.append(line)

    result = _CPP_HEADER + "\n".join(body_lines)

    # Add inline comments to common patterns
    result = result.replace(
        "int main()",
        "// Entry point\nint main()"
    ).replace(
        "int main(){",
        "// Entry point\nint main() {"
    ).replace(
        "cin >>", "// Read input\n    cin >>"
    )
    return result


# ── Java transformer ────────────────────────────────────────────────────────

_JAVA_TEMPLATE = """\
import java.util.*;
import java.io.*;

/**
 * Solution class for competitive programming problem.
 * Uses standard Java I/O for efficient input processing.
 */
public class Solution {{
    /**
     * Main entry point.
     * @param args command-line arguments (unused)
     * @throws Exception if I/O fails
     */
    public static void main(String[] args) throws Exception {{
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        // Original solution logic below
{indented}
    }}
}}
"""


def _transform_java(code: str) -> str:
    lines = code.splitlines()
    body = []
    inside_main = False
    brace_depth = 0

    for line in lines:
        s = line.strip()
        if "public static void main" in s or "public static void Main" in s:
            inside_main = True
            brace_depth = 0
        if inside_main:
            brace_depth += s.count("{") - s.count("}")
            if brace_depth <= 0 and s.endswith("}") and body:
                break
            if s and not s.startswith("public static void main"):
                body.append("        " + s)

    if not body:
        # Fallback: just indent the whole code
        for line in lines:
            body.append("        " + line)

    return _JAVA_TEMPLATE.format(indented="\n".join(body))


# ── Dispatcher ─────────────────────────────────────────────────────────────

_TRANSFORMERS = {
    ".py":   _transform_python,
    ".cpp":  _transform_cpp,
    ".cc":   _transform_cpp,
    ".java": _transform_java,
}


def transform(code: str, suffix: str) -> str:
    fn = _TRANSFORMERS.get(suffix.lower())
    if fn is None:
        return code  # return as-is for unknown extensions
    try:
        return fn(code)
    except Exception as e:
        logger.warning(f"Transform failed ({suffix}): {e} — using original")
        return code


# ── Main ───────────────────────────────────────────────────────────────────

def main() -> None:
    logger.info("=== Synthetic AI Solution Generator ===")

    if not SELECTED_PATH.exists():
        logger.error(f"No selected_problems.txt at {SELECTED_PATH}. Run download_hf_dataset.py first.")
        sys.exit(1)

    problems = [p for p in SELECTED_PATH.read_text().splitlines() if p.strip()]
    logger.info(f"Generating synthetic solutions for {len(problems)} problem(s)")

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    total_written = 0

    for pid in tqdm(problems, desc="Problems", unit="prob"):
        src_dir = RAW_DIR / pid
        if not src_dir.exists():
            logger.warning(f"No raw dir for {pid} — skipping")
            continue

        out_dir = GENERATED_DIR / pid
        out_dir.mkdir(parents=True, exist_ok=True)

        human_files = [f for f in sorted(src_dir.iterdir()) if f.is_file()]
        per_lang_count: dict[str, int] = {}

        for src_file in human_files:
            suffix = src_file.suffix.lower()
            if suffix not in _TRANSFORMERS:
                continue

            # Keep at most AI_SOLUTIONS_PER_PROBLEM per language
            lang_count = per_lang_count.get(suffix, 0)
            if lang_count >= AI_SOLUTIONS_PER_PROBLEM:
                continue

            code = src_file.read_text(encoding="utf-8", errors="replace")
            if len(code.strip()) < 20:
                continue

            transformed = transform(code, suffix)

            out_name = f"{MODEL_TAG}_{suffix.lstrip('.')}_{lang_count:03d}{suffix}"
            out_path = out_dir / out_name
            if not out_path.exists():
                out_path.write_text(transformed, encoding="utf-8")
                total_written += 1

            per_lang_count[suffix] = lang_count + 1

    logger.info(f"Written {total_written} synthetic AI solutions → {GENERATED_DIR}")
    logger.info("Done. Run scripts/build_dataset.py next.")


if __name__ == "__main__":
    main()
